/**
 * 全局根符号的唯一来源。
 *
 * v1 把「代码引用了一个没有本地绑定的名字」分成两类：
 *
 * - LANGUAGE_BUILTIN_ROOTS：ECMAScript 语言内建。所有受支持的宿主上语义一致，
 *   不承载任何宿主运行时依赖，因此可以走正常折叠比较。
 * - HOST_GLOBAL_ROOTS：宿主或模块系统注入的名字。是否可折叠取决于目标运行时，
 *   必须由证据判定。
 *
 * 两份清单曾被 analyzer（判定 unresolved_global）与 language probe（可观测根集合）
 * 各自维护，导致探针认识、analyzer 不认识的内建被误判为 unresolved_global。
 * 现在两处共用本文件，避免再次漂移。
 */

export const LANGUAGE_BUILTIN_ROOTS = Object.freeze([
  "AggregateError",
  "Array",
  "ArrayBuffer",
  "Atomics",
  "BigInt",
  "BigInt64Array",
  "BigUint64Array",
  "Boolean",
  "DataView",
  "Date",
  "Error",
  "EvalError",
  "FinalizationRegistry",
  "Float32Array",
  "Float64Array",
  "Function",
  "Infinity",
  "Int8Array",
  "Int16Array",
  "Int32Array",
  "Intl",
  "JSON",
  "Map",
  "Math",
  "NaN",
  "Number",
  "Object",
  "Promise",
  "Proxy",
  "RangeError",
  "ReferenceError",
  "Reflect",
  "RegExp",
  "Set",
  "SharedArrayBuffer",
  "String",
  "Symbol",
  "SyntaxError",
  "TypeError",
  "Uint8Array",
  "Uint8ClampedArray",
  "Uint16Array",
  "Uint32Array",
  "URIError",
  "WeakMap",
  "WeakRef",
  "WeakSet",
  "decodeURI",
  "decodeURIComponent",
  "encodeURI",
  "encodeURIComponent",
  "escape",
  "eval",
  "globalThis",
  "isFinite",
  "isNaN",
  "parseFloat",
  "parseInt",
  "undefined",
  "unescape",
]);

export const HOST_GLOBAL_ROOTS = Object.freeze([
  "AbortController",
  "AbortSignal",
  "App",
  "Behavior",
  "Blob",
  "BroadcastChannel",
  "Buffer",
  "Component",
  "CustomEvent",
  "Event",
  "EventTarget",
  "File",
  "FormData",
  "Headers",
  "MessageChannel",
  "MessagePort",
  "MutationObserver",
  "Page",
  "Request",
  "Response",
  "TextDecoder",
  "TextEncoder",
  "URL",
  "URLSearchParams",
  "WebSocket",
  "XMLHttpRequest",
  "clearImmediate",
  "clearInterval",
  "clearTimeout",
  "console",
  "crypto",
  "document",
  "exports",
  "fetch",
  "getApp",
  "getCurrentPages",
  "global",
  "localStorage",
  "location",
  "module",
  "navigator",
  "process",
  "queueMicrotask",
  "require",
  "sessionStorage",
  "setImmediate",
  "setInterval",
  "setTimeout",
  "window",
  "wx",
]);
